import { users } from "../config/mongoCollections.js";
const professors = [
  {
    firstName: "Shaoib",
    lastName: "Kalawant",
    email: "skalawan@stevens.edu",
    role: "PROFESSOR",
    department: "COMPUTER_SCIENCE",
    bio: null,
    password: "password123",
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "ajohnson@stevens.edu",
    role: "PROFESSOR",
    department: "BIOMEDICAL_ENGINEERING",
    bio: null,
    password: "alice@321",
  },
  {
    firstName: "Bob",
    lastName: "Smith",
    email: "bsmith@stevens.edu",
    role: "PROFESSOR",
    department: "CHEMISTRY_AND_CHEMICAL_BIOLOGY",
    bio: null,
    password: "bob12345",
  },
  {
    firstName: "Clara",
    lastName: "Evans",
    email: "cevans@stevens.edu",
    role: "PROFESSOR",
    department: "ELECTRICAL_AND_COMPUTER_ENGINEERING",
    bio: null,
    password: "clara@456",
  },
  {
    firstName: "David",
    lastName: "Williams",
    email: "dwilliams@stevens.edu",
    role: "PROFESSOR",
    department: "CIVIL_ENVIRONMENTAL_AND_OCEAN_ENGINEERING",
    bio: null,
    password: "david$789",
  },
  {
    firstName: "Emily",
    lastName: "Brown",
    email: "ebrown@stevens.edu",
    role: "PROFESSOR",
    department: "MECHANICAL_ENGINEERING",
    bio: null,
    password: "emily*987",
  },
  {
    firstName: "Frank",
    lastName: "Miller",
    email: "fmiller@stevens.edu",
    role: "PROFESSOR",
    department: "PHYSICS",
    bio: null,
    password: "frank4567",
  },
  {
    firstName: "Grace",
    lastName: "Lee",
    email: "glee@stevens.edu",
    role: "PROFESSOR",
    department: "SYSTEMS_AND_ENTERPRISES",
    bio: null,
    password: "grace2023",
  },
  {
    firstName: "Henry",
    lastName: "Wilson",
    email: "hwilson@stevens.edu",
    role: "PROFESSOR",
    department: "MATHEMATICAL_SCIENCES",
    bio: null,
    password: "henry999",
  },
  {
    firstName: "Isabella",
    lastName: "Garcia",
    email: "igarcia@stevens.edu",
    role: "PROFESSOR",
    department: "CHEMICAL_ENGINEERING_AND_MATERIALS_SCIENCE",
    bio: null,
    password: "isabella321",
  },
  {
    firstName: "Jack",
    lastName: "Martinez",
    email: "jmartinez@stevens.edu",
    role: "PROFESSOR",
    department: "BIOMEDICAL_ENGINEERING",
    bio: null,
    password: "jackpass1",
  },
  {
    firstName: "Karen",
    lastName: "Rodriguez",
    email: "krodriguez@stevens.edu",
    role: "PROFESSOR",
    department: "COMPUTER_SCIENCE",
    bio: null,
    password: "karen1234",
  },
  {
    firstName: "Liam",
    lastName: "Hernandez",
    email: "lhernandez@stevens.edu",
    role: "PROFESSOR",
    department: "MECHANICAL_ENGINEERING",
    bio: null,
    password: "liam5678",
  },
  {
    firstName: "Mia",
    lastName: "Lopez",
    email: "mlopez@stevens.edu",
    role: "PROFESSOR",
    department: "PHYSICS",
    bio: null,
    password: "mia!432",
  },
  {
    firstName: "Noah",
    lastName: "Perez",
    email: "nperez@stevens.edu",
    role: "PROFESSOR",
    department: "SYSTEMS_AND_ENTERPRISES",
    bio: null,
    password: "noah$123",
  },
  {
    firstName: "Olivia",
    lastName: "King",
    email: "oking@stevens.edu",
    role: "PROFESSOR",
    department: "CIVIL_ENVIRONMENTAL_AND_OCEAN_ENGINEERING",
    bio: null,
    password: "olivia999",
  },
  {
    firstName: "Paul",
    lastName: "Scott",
    email: "pscott@stevens.edu",
    role: "PROFESSOR",
    department: "MATHEMATICAL_SCIENCES",
    bio: null,
    password: "paul1234",
  },
  {
    firstName: "Quinn",
    lastName: "Adams",
    email: "qadams@stevens.edu",
    role: "PROFESSOR",
    department: "CHEMISTRY_AND_CHEMICAL_BIOLOGY",
    bio: null,
    password: "quinn@pass",
  },
  {
    firstName: "Ryan",
    lastName: "Baker",
    email: "rbaker@stevens.edu",
    role: "PROFESSOR",
    department: "ELECTRICAL_AND_COMPUTER_ENGINEERING",
    bio: null,
    password: "ryan567",
  },
  {
    firstName: "Sophia",
    lastName: "Nelson",
    email: "snelson@stevens.edu",
    role: "PROFESSOR",
    department: "CHEMICAL_ENGINEERING_AND_MATERIALS_SCIENCE",
    bio: null,
    password: "sophia123",
  },
];

console.log(professors.length);
